services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./app.db:/app/app.db
    environment:
      - NODE_ENV=production
    restart: always
