services:
  # Frontend Service
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=/api # Mantido, pois o Nginx fará o proxy
    depends_on:
      - backend # Mantém a dependência para garantir que o backend inicie antes
    networks:
      - pong-network

  # Backend Service
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
      - /app/node_modules
      - db-data:/app/data
      - ./src/backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=sqlite:./data/app.db
      - CORS_ORIGIN=https://localhost,http://localhost
    depends_on:
      database:
        condition: service_started
      blockchain:
        condition: service_started
    healthcheck: # <-- ADICIONADO: Healthcheck para o Backend
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Testa o endpoint /health
      interval: 10s # Verifica a cada 10 segundos
      timeout: 5s   # Tempo limite para a verificação
      retries: 5    # Número de tentativas antes de considerar falha
      start_period: 20s # Tempo para o serviço iniciar antes de começar a testar
    networks:
      - pong-network

  # Database Service (SQLite will be file-based, but we can use a volume)
  database:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - db-data:/data
    networks:
      - pong-network

  # Blockchain Development Environment (Ganache for Avalanche testing)
  blockchain:
    image: trufflesuite/ganache:latest
    ports:
      - "7545:8545"
    command: >
      --host 0.0.0.0
      --port 8545
      --networkId 43112
      --accounts 10
      --mnemonic "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    networks:
      - pong-network

  # Nginx Reverse Proxy with SSL
  nginx:
    build:
      context: ./src/docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/docker/nginx/ssl:/etc/nginx/ssl
      - ./src/docker/certbot/conf:/etc/letsencrypt:ro
      - ./src/docker/certbot/www:/var/www/certbot:ro
      - nginx-cache:/var/cache/nginx
    environment:
      - SSL_DOMAIN=localhost
      - SSL_COUNTRY=PT
      - SSL_STATE=Porto
      - SSL_CITY=Porto
      - SSL_ORG=ft_transcendence
      - SSL_OU=Development
      - WAIT_FOR_SERVICES=true
    depends_on:
      frontend:
        condition: service_started
      backend: # <-- ALTERADO: Agora depende do healthcheck do backend
        condition: service_healthy # <-- Garante que o backend está pronto antes do Nginx
    networks:
      - pong-network
    restart: unless-stopped

  # Certbot for Let's Encrypt (optional)
  certbot:
    image: certbot/certbot
    volumes:
      - ./src/docker/certbot/conf:/etc/letsencrypt
      - ./src/docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - pong-network
    profiles:
      - production

volumes:
  db-data:
  nginx-cache:

networks:
  pong-network:
    driver: bridge
